name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/layer-and-layerset-build.yaml@fix-gh-release-how-to-consume-section-2
    permissions:
      contents: write
      packages: write
      checks: write
